apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: nginx-hello.com
      http: 
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: nginx-hello-service
                port: 
                  number: 32769
